=== rsugio/komar/src/main/xsd-generate/application-j2ee-engine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="application-j2ee-engine">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="reference" type="referenceType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="library-loader" type="libraryLoaderType" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="classpath" minOccurs="0"/>
				<xs:element ref="provider-name" minOccurs="0"/>
				<xs:element name="modules-additional" type="modules-additionalType" minOccurs="0"/>
				<xs:element name="fail-over-enable" type="fail-over-enableType" minOccurs="0"/>
				<xs:element name="start-up" type="start-upType" minOccurs="0"/>
				<xs:element ref="java-version" minOccurs="0"/>
				<xs:element name="exclude-default-reference" type="excludeDefaultReferenceType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="classpath" type="xs:string"/>
	<xs:element name="container-type" type="xs:string"/>
	<xs:element name="entry-name" type="xs:string"/>
	<xs:element name="java-version" type="xs:string"/>
	<xs:complexType name="fail-over-enableType" abstract="true">
		<xs:sequence/>
	</xs:complexType>
	<xs:simpleType name="ModeType_disable">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="disable"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="fail-over-enableType_disable">
		<xs:complexContent>
			<xs:extension base="fail-over-enableType">
				<xs:attribute name="mode" type="ModeType_disable" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="ModeType_enable">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="on_request"/>
			<xs:enumeration value="on_attribute"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="fail-over-enableType_enable">
		<xs:complexContent>
			<xs:extension base="fail-over-enableType">
				<xs:attribute name="mode" type="ModeType_enable" use="required"/>
				<xs:attribute name="scope" use="optional" default="instance_local">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="instance_local"/>
							<xs:enumeration value="cluster_wide"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="delta" use="optional" default="off">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="on"/>
							<xs:enumeration value="off"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="start-upType">
		<xs:attribute name="mode" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="manual"/>
					<xs:enumeration value="lazy"/>
					<xs:enumeration value="always"/>
					<xs:enumeration value="disabled"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="moduleType">
		<xs:sequence>
			<xs:element ref="entry-name"/>
			<xs:element ref="container-type" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="modules-additionalType">
		<xs:sequence>
			<xs:element name="module" type="moduleType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="provider-name" type="xs:string"/>
	<xs:complexType name="referenceType">
		<xs:sequence>
			<xs:element name="reference-target" type="reference-targetType"/>
		</xs:sequence>
		<xs:attribute name="reference-type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="hard"/>
					<xs:enumeration value="weak"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="prepend" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="excludeDefaultReferenceType">
		<xs:sequence>
			<xs:element name="reference-target" type="reference-targetType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="reference-targetType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="target-type" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="application"/>
							<xs:enumeration value="library"/>
							<xs:enumeration value="service"/>
							<xs:enumeration value="interface"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="provider-name" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="libraryLoaderType">
		<xs:sequence>
			<xs:element name="reference" type="libLoaderReferenceType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="libLoaderReferenceType">
		<xs:sequence>
			<xs:element name="reference-target" type="libLoaderReferenceTargetType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="libLoaderReferenceTargetType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="target-type" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="library"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="provider-name" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== rsugio/komar/src/test/resources/set07/application-j2ee-engine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application-j2ee-engine SYSTEM 'application-j2ee-engine.dtd'>
<application-j2ee-engine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="application-j2ee-engine.xsd"
        >
<!-- ume-permissions for servlet -->
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="library">com.sap.security.api.sda</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="library">iaik.lib.facade</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="library">engine.jee5.facade</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="library">com.sap.base.technology.facade</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="library">com.sap.aii.af.lib.facade</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="library">tc~bl~httpclient~lib</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="interface">com.sap.aii.af.ifc.facade</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="service">tc/je/appconfiguration/api</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="service">com.sap.aii.af.svc.facade</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="service">com.sap.aii.adapter.xi.svc</reference-target>
</reference>
<reference reference-type="weak">
	<reference-target provider-name="sap.com" target-type="application">com.sap.xi.directory</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="library">com.sap.aii.adapter.odata.lib</reference-target>
</reference>
<reference reference-type="hard">
	<reference-target provider-name="sap.com" target-type="application">com.sap.aii.adapter.picao.util.app</reference-target>
</reference>

<fail-over-enable mode="disable"/>
</application-j2ee-engine>
